### ISSUE TITLE
File missing in refs

### ISSUE THREAD

**Issue by teisnotte** [emmamglass/reconstructor#1]
Hello there,

I think the refs folder is missing in the build, with following error:

`FileNotFoundError: [Errno 2] No such file or directory: '/Users/anaconda3/lib/python3.9/site-packages/reconstructor/refs/gene_modelseed.pickle'`

**Comment by emmamglass** [comment]
Hello,
We have been actively developing and making reconstructor better, so first please ensure that you have downloaded the most recent version of reconstructor (should be version 1.0.73).

The /refs folder is not included in the build, but is created/filled with dependencies while running the required test suite (outlined in the installation guide in the readme).

To run the test suite use the following line:
```
python -m reconstructor --test yes
```

It should take around an hour for the test suite to run successfully.

**Comment by teisnotte** [comment]
Hello Emma, 

Thanks! Yes, I got the new version from pip source. The folder is resolved by adding those files from 0.01 version. However, what's the cobra version you are using?

The following error came up:
```
File "/Users/opt/anaconda3/lib/python3.9/site-packages/reconstructor/__main__.py", line 286, in _gapfill_model
    if step == 1: new_rxns.append(deepcopy(universal.reactions.get_by_id(obj)))
File "/Users/opt/anaconda3/lib/python3.9/site-packages/cobra/core/dictlist.py", line 57, in get_by_id
    return list.__getitem__(self, self._dict[id])
KeyError: 'growth'
```

**Comment by emmamglass** [comment]
The COBRApy version dependency should be version 0.22.1, which should be installed when you install reconstructor via pip.

I think the error you are having is that the glpk_interface.py file is bad. This is something that I have come across, and have included a corrected glpk_interface.py file in the 0.0.1 releases.

 This file should have been downloaded and automatically replace your existing glpk_interface.py file when running the ```python -m reconstructor --test yes``` command, but it appears that did not work for you. For now, if you can replace the existing glpk_interface.py file at this path ``` /Users/opt/anaconda3/lib/python3.9/site-packages/optlang/glpk_interface.py```, with the glpk_interface.py file that is in the releases 0.0.1, it should work.

I will work on trying to get this to download automatically in the next version of Reconstructor.

**Comment by teisnotte** [comment]
Thank you! Pretty much fixed, though the naming doesn't match the bigg model I use. I'm wondering if the seed names will be automatically converted to bigg or mnmx to match the compound?
